"""Add diseases table and risk columns to disease_scans"""

from alembic import op
import sqlalchemy as sa
import uuid

# revision identifiers, used by Alembic.
revision = "009"
# The down_revision should match the latest existing revision ID (currently "008")
# This will be updated automatically if generated via alembic revision command.
down_revision = "008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create diseases table
    op.create_table(
        "diseases",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4),
        sa.Column("class_key", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("description", sa.String(1000), nullable=False),
        sa.Column("causes", sa.JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column("recommendations", sa.JSON, nullable=False, server_default=sa.text("'[]'")),
        sa.Column("severity_default", sa.String(20), nullable=False, server_default=sa.text("'low'")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )

    # 2. Add risk columns to disease_scans (already present in model but not in DB)
    op.add_column("disease_scans", sa.Column("risk_level", sa.String(20), nullable=True))
    op.add_column("disease_scans", sa.Column("risk_reason", sa.String(500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("disease_scans", "risk_reason")
    op.drop_column("disease_scans", "risk_level")
    op.drop_table("diseases")
    # ### end Alembic commands ###
